### ISSUE TITLE
Planet Wide Mining is missing some resouces

### ISSUE THREAD

**Issue by radflag622** [GoToNightmare/DSP-PlanetwideMining#1]
The miner does not have all the ores listed.  Optical Gratling Crystal does not appear mineable. This is the only one I have encountered so far.  Looking for a fix soon.  
Also you cannot use the miner as a regular miner anymore.
Thanks

**Comment by GoToNightmare** [comment]
`Optical Gratling Crystal` going to add them, and check all resources.

Probably need some kind UI inication which resource if active.

**Comment by radflag622** [comment]
Thanks

**Comment by GoToNightmare** [comment]
Updated, check releases or thunderstore.
