### ISSUE TITLE
Mod doesn't work v0.0.7

### ISSUE THREAD

**Issue by Norman-Chang** [GoToNightmare/DSP-PlanetwideMining#10]
setup mod as usual，but it seems doesn't work when i press PAGEUP

**Comment by GoToNightmare** [comment]
Sorry its bepinex issue, i'll reupload for old version

**Comment by GoToNightmare** [comment]
@Norman-Chang https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release
Could u try this one

**Comment by Norman-Chang** [comment]
> @Norman-Chang https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release Could u try this one

OK, it‘s worked
