### ISSUE TITLE
New version breaks hotkey and other mod

### ISSUE THREAD

**Issue by AaronMDavis** [GoToNightmare/DSP-PlanetwideMining#11]
In version 0.0.7 page-down works to cycle backwards for the miner resource. This no longer works in 0.0.8.
Same thing for the mod LazyOutposting, old version doesn't break the water pump from working without actual water, new version breaks that.

**Comment by GoToNightmare** [comment]
@AaronMDavis BepInEx version?
could you dm me in discord Tony#7977

**Comment by AaronMDavis** [comment]
5.4.17
