### ISSUE TITLE
We need to add an additional shortcut key

### ISSUE THREAD

**Issue by MRevenger** [GoToNightmare/DSP-PlanetwideMining#12]
Sometimes when switching between ore veins, we may miss what we need due to one more press, or the minerals we need are on the previous one, but we can only scroll down. We need two buttons, PgUP and PgDN, to better switch between them

**Comment by GoToNightmare** [comment]
Added
https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release
