### ISSUE TITLE
No ico and PgDn problem

### ISSUE THREAD

**Issue by CaptainCrap** [GoToNightmare/DSP-PlanetwideMining#14]
So i've updated the mod, and first things first - theres no ico for Oil while searching for mineable resourcec via miner (its easy to just skip it and it took me solid 2 minutes to figure out what im missing xd) and secondly, while using page down to locate skipped mineral it just goes straight pass the iron. Pg up show iron as mineable but when you try to go backwards it just skips it. Rest is fine, just skips iron. Is it due to added oil it skips it using page down or is it really something bad that had happened ;x ?

**Comment by GoToNightmare** [comment]
![image](https://github.com/GoToNightmare/DSP-PlanetwideMining/assets/34166246/adfe2a12-0672-4131-a002-e70f2924ead3)
 🤔

**Comment by GoToNightmare** [comment]
> Pg up show iron as mineable but when you try to go backwards it just skips it.

Fixed
https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release

**Comment by CaptainCrap** [comment]
> ![image](https://user-images.githubusercontent.com/34166246/260271569-adfe2a12-0672-4131-a002-e70f2924ead3.png) 🤔

Huh... Well that's odd, maybe my keyboard was just being funky? I was using MK1 miner but that shouldnt be the issue. Welp, no worries then xD
