### ISSUE TITLE
Mod appears to add speed controls to numpad

### ISSUE THREAD

**Issue by PiggyWhiskey** [GoToNightmare/DSP-PlanetwideMining#15]
This mod appears to add Time/Speed controls to the Numpad with no option to disable.
It seems to be NUM 1-4 for various speeds.

Requesting a Config to disable these, or separate them to another mod.

**Comment by GoToNightmare** [comment]
@PiggyWhiskey https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release
