### ISSUE TITLE
mod compatibility

### ISSUE THREAD

**Issue by xxldm** [GoToNightmare/DSP-PlanetwideMining#19]
<创世之书> mod添加了新的矿脉,  本mod无法采集新增的矿脉, 是否可以参考以下mod, 通过`LDB.veins.dataArray`获取所有矿脉用以兼容其余mod

google translate: <Book of Genesis> mod adds new veins. This mod cannot collect the newly added veins. Can you refer to the following mod to obtain all veins through `LDB.veins.dataArray` to be compatible with other mods?

https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/GUIDraw.cs#L1022C28-L1022C47

**Comment by GoToNightmare** [comment]
> <创世之书> mod添加了新的矿脉, 本mod无法采集新增的矿脉, 是否可以参考以下mod, 通过`LDB.veins.dataArray`获取所有矿脉用以兼容其余mod
> 
> google translate: mod adds new veins. This mod cannot collect the newly added veins. Can you refer to the following mod to obtain all veins through `LDB.veins.dataArray` to be compatible with other mods?
> 
> https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/GUIDraw.cs#L1022C28-L1022C47

Could u reference a line of code that adds resource vein to planet vein pool?

**Comment by xxldm** [comment]
https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/Models/VeinControlProperty.cs#L286C29-L286C72

**Comment by GoToNightmare** [comment]
> 这个看起来是添加数量 google translate: This looks like adding quantity
> 
> https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/Models/VeinControlProperty.cs#L286C29-L286C72
> 
> 这个看起来是新增矿脉 google translate: This looks like a new mineral vein.
> 
> https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/Models/VeinControlProperty.cs#L316

@xxldm Could you check release page, updated it to use `GameMain.localPlanet`

https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release

**Comment by xxldm** [comment]
> > 这个看起来是添加数量 谷歌翻译：这看起来像添加数量
> > https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/Models/VeinControlProperty.cs#L286C29-L286C72
> > 这个看起来是新增矿脉谷歌翻译：这看起来像一个新的矿脉。
> > https://github.com/blacksnipebiu/Multifunction_mod/blob/43b67dd770ef9161dc52b1ab749cc893a111a726/Multifunction_mod/Models/VeinControlProperty.cs#L316
> 
> @xxldm 您能否检查发布页面，将其更新为使用 `GameMain.localPlanet`
> 
> https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release
> 
> [43ad96d#diff-845d4723d587242234157bb33c79fd9e32ddff4d78933f144d12ea052935c322R174](https://github.com/GoToNightmare/DSP-PlanetwideMining/commit/43ad96dd0542023bcb3689c3257ac92961b91052#diff-845d4723d587242234157bb33c79fd9e32ddff4d78933f144d12ea052935c322R174)

您好, 经过测试, 小矿机退回到了官方功能. 大矿机与上一个mod版本相同, 无法切换到新增矿脉.
google translate: Hello, after testing, the small miner has returned to the official function. The large miner is the same as the previous mod version and cannot be switched to the newly added ore vein.

这个地方是否需要同步修改?
google translate: Does this place need to be modified synchronously?
https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L114C39-L114C52

**Comment by GoToNightmare** [comment]
> 您好, 经过测试, 小矿机退回到了官方功能. 大矿机与上一个mod版本相同, 无法切换到新增矿脉.
> google translate: Hello, after testing, the small miner has returned to the official function. The large miner is the same as the previous mod version and cannot be switched to the newly added ore vein.

Fixed
https://github.com/GoToNightmare/DSP-PlanetwideMining/commit/3a4cfa07a228b865c40512b0725e0305a0250811
https://github.com/GoToNightmare/DSP-PlanetwideMining/releases/tag/release

**Comment by GoToNightmare** [comment]
> 这个地方是否需要同步修改?
> google translate: Does this place need to be modified synchronously?
> https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L114C39-L114C52

It seems alright, do you have any issues with that?

**Comment by xxldm** [comment]
> > 这个地方是否需要同步修改?
> > google translate: Does this place need to be modified synchronously?
> > https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L114C39-L114C52
> 
> It seems alright, do you have any issues with that?

我通过`KeyCode.PageUp`无法找到新增的矿脉
google translate: I can't find the new vein through `KeyCode.PageUp`

**Comment by GoToNightmare** [comment]
> > > 这个地方是否需要同步修改?
> > > google translate: Does this place need to be modified synchronously?
> > > https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L114C39-L114C52
> > 
> > 
> > It seems alright, do you have any issues with that?
> 
> 我通过`KeyCode.PageUp`无法找到新增的矿脉 google translate: I can't find the new vein through `KeyCode.PageUp`

Do u have a discord? Could you add me `tony_gtn`, so we could find whats the problem faster
`KeyCode.PageUp` Only switches target resource type. Maybe the code that checking planet resources is bugged.
Does it actually searching resources for you?

**Comment by GoToNightmare** [comment]
@xxldm Im also trying to install ur mod to debug this issue, and need some help, bepinex doesnt load it for some reason.

**Comment by xxldm** [comment]
> > > > 这个地方是否需要同步修改?
> > > > google translate: Does this place need to be modified synchronously?
> > > > https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L114C39-L114C52
> > > 
> > > 
> > > It seems alright, do you have any issues with that?
> > 
> > 
> > 我通过`KeyCode.PageUp`无法找到新增的矿脉 google translate: I can't find the new vein through `KeyCode.PageUp`
> 
> Do u have a discord? Could you add me `tony_gtn`, so we could find whats the problem faster `KeyCode.PageUp` Only switches target resource type. Maybe the code that checking planet resources is bugged. Does it actually searching resources for you?

`PageUp`无法切换到新增的矿脉, 不是因为`ResourceTypes`是静态的吗? 我看你代码, 切换资源类型就是循环该列表, 并未检查星球资源.
google translate: `PageUp` cannot switch to the newly added mineral vein, isn't it because `ResourceTypes` is static? From what I saw in your code, switching resource types just loops through the list, without checking the planetary resources.

https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L50-L58
https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L96-L115
https://github.com/GoToNightmare/DSP-PlanetwideMining/blob/43ad96dd0542023bcb3689c3257ac92961b91052/PlanetwideMining/PlanetwideMining/PlanetwideMining.cs#L130-L148

我所有的mod全部是使用`r2modman`从[thunderstore](https://thunderstore.io/c/dyson-sphere-program/)下载
google translate: All my mods are downloaded from [thunderstore](https://thunderstore.io/c/dyson-sphere-program/) using `r2modman`.

添加了新矿脉的mod名为[`创世之书`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/)
google translate: The mod that adds the new ore vein is called [`GenesisBook`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/)

上方提供的参考代码mod名为[`op多功能`](https://thunderstore.io/c/dyson-sphere-program/p/blacksnipebiu/Multfuntion_mod/)
google translate: The reference code mod provided above is named [`Multfuntion mod`](https://thunderstore.io/c/dyson-sphere-program/p/blacksnipebiu/Multfuntion_mod/)

**Comment by GoToNightmare** [comment]
> google translate: `PageUp` cannot switch to the newly added mineral vein, isn't it because `ResourceTypes` is static? From what I saw in your code, switching resource types just loops through the list, without checking the planetary resources.

Thats correct, it doesnt check planet resources, and in case that you dont have active resource on the planet, it wont find any.
So in order to find existed resources, you have to `PageUp` multiple times, untill you got a resource that planet have.

**Comment by GoToNightmare** [comment]
![image](https://github.com/user-attachments/assets/8a5d64ba-4477-4cd7-a063-907bf37a0d86)

Newly added veins works for me, do u have any issues? @xxldm

**Comment by xxldm** [comment]
抱歉, 是我没有表述清楚, 我说的新矿脉, 是指 [`创世之书`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/) 新增了多种名叫`铝矿\放射性矿物\钨矿……`这种官方没有的矿物.
google translate: Sorry, I didn't explain it clearly. The new mineral veins I mentioned refer to the new minerals added to the [`GenesisBook`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/) called `aluminum ore, radioactive ore, tungsten ore...` that are not officially available.
![PixPin_2024-07-22_10-06-26](https://github.com/user-attachments/assets/78feb6f2-a29d-4172-b088-11711edaa0ad)

我突然发现对方有尝试作兼容, 但是不知道为啥没有生效
google translate: I suddenly found that the other party tried to make it compatible, but I don't know why it didn't work.
https://github.com/Awbugl/ProjectGenesis/blob/77c6dffcc4c2e6495a62888a6cbcd8c33715d4af/src/Compatibility/PlanetwideMining.cs#L13-L26

**Comment by GoToNightmare** [comment]
> 抱歉, 是我没有表述清楚, 我说的新矿脉, 是指 [`创世之书`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/) 新增了多种名叫`铝矿\放射性矿物\钨矿……`这种官方没有的矿物. google translate: Sorry, I didn't explain it clearly. The new mineral veins I mentioned refer to the new minerals added to the [`GenesisBook`](https://thunderstore.io/c/dyson-sphere-program/p/HiddenCirno/GenesisBook/) called `aluminum ore, radioactive ore, tungsten ore...` that are not officially available. ![PixPin_2024-07-22_10-06-26](https://private-user-images.githubusercontent.com/38677850/350817970-78feb6f2-a29d-4172-b088-11711edaa0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzA0OTUsIm5iZiI6MTcyMTYzMDE5NSwicGF0aCI6Ii8zODY3Nzg1MC8zNTA4MTc5NzAtNzhmZWI2ZjItYTI5ZC00MTcyLWIwODgtMTE3MTFlZGFhMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmViODA0YzVhMzNmN2ZmZWVjMGYxZmVjZTdkYjRhOGY1MDNjZTFiNTdkZWU2NDYyYjlhNzg0OWNkMTA0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VbKfEo2v7njQQPqKk1Fco4c_XqfAWNzPbgcQ3mj-ujQ)
> 
> 我突然发现对方有尝试作兼容, 但是不知道为啥没有生效 google translate: I suddenly found that the other party tried to make it compatible, but I don't know why it didn't work. https://github.com/Awbugl/ProjectGenesis/blob/77c6dffcc4c2e6495a62888a6cbcd8c33715d4af/src/Compatibility/PlanetwideMining.cs#L13-L26

Ahh, I see, I know how to fix

**Comment by xxldm** [comment]
目前测试没有发现问题. 谢谢您, 辛苦了.
google translate: No problems were found in the test so far. Thank you for your hard work.
